---
title: "Scraping"
author: "Adirupa Nag"
date: "2023-03-27"
output: html_document
---

```{r}
library(tidyverse)
library (rvest)
library(dplyr)
library(xml2)
library (stringr)
library(robotstxt)
library(ggplot2)
library(forcats)
```

```{r}
bobsburger= data.frame()
  for (season in 1:12) {
    link= paste0("https://www.imdb.com/title/tt1561755/episodes?season=", season)
    robotstxt::paths_allowed(link) 
    page = read_html(link)
    
season <- page %>%
    html_nodes('#episode_top') %>% 
    html_text() 
 
  
  name<-page%>%
    html_nodes('#episodes_content strong a') %>% 
    html_text()  
  
  rating <- page %>%
    html_nodes('.ipl-rating-star.small .ipl-rating-star__rating') %>% 
    html_text() 
   
  number_of_rating <- page %>%
    html_nodes('.ipl-rating-star__total-votes') %>% 
    html_text() 
   
  summary<- page %>%
    html_nodes('.item_description') %>% 
    html_text() 
  
  # Combine data for current season into a data frame
  season_data <- data.frame(season = season, title = name, rating = rating, number_of_rating=number_of_rating,summary=summary)
  
  # Add current season's data to overall data frame
  bobsburger <- rbind(bobsburger, season_data)
  Sys.sleep(5)
}


write.csv(bobsburger, "bobs_burger_episode.csv",row.names = FALSE)

```

